// src/vistas/menuprincipal/MainScreen.vue
<template>
	<div class="menu">
		<router-link :to="{name: 'GameScreen'}">
			<button class="boton boton-new-game">New game</button>
		</router-link>
		<button class="boton boton-load-game">Load game</button>
		<router-link :to="{name: 'CreadorEntidades'}">
			<button class="boton boton-creador-de-entidades">Entity creator</button>
		</router-link>
		<button class="boton boton-salir">Exit</button>
	</div>
</template>

<script lang="ts">
import { Component, Vue } from 'vue-property-decorator';

@Component
export default class MainScreen extends Vue {
}
</script>

<style scoped>
.menu {
	display: flex;
	justify-content: space-evenly;
}

.boton {
	border-radius: 3px;
	border: 3px solid;
	font-weight: bolder;
	margin-bottom: 5px;
	width: 150px;
	align-content: center;
	cursor: pointer;
}

.boton:not(hover) {
	transition: 2s ease;
}

.boton:hover {
	transition: 0.5s;
	filter: brightness(150%);
	border-radius: 15px;
}

.boton-new-game {
	background-color: yellow;
	border-color: orangered;
	color: orangered;
}

.boton-load-game {
	background-color: greenyellow;
	border-color: green;
	color: green;
}

.boton-creador-de-entidades {
	background-color: cyan;
	border-color: darkblue;
	color: darkblue;
}

.boton-salir {
	background-color: lightblue;
	border-color: darkslategrey;
	color: darkslategrey;
}
</style>

// src/vistas/menuprincipal/MainScreen.tsx
import React from "react";
import EntidadFactory from "../../entidades/EntidadFactory";
import { crearMundoInicial } from "../../mapa/builder/WorldBuilder";
import "./styles.css";
import { usarComoPlayer } from '../../store/store';

export default class MainScreen extends React.Component {

	render() {
		return (
			<div className="menu">
				<button onClick={ this.comenzarNuevoJuego } className="boton boton-new-game">New game</button>
				<button className="boton boton-load-game">Load game</button>
				{/* <router-link :to="{name: 'CreadorEntidades'}"> */ }
				<button className="boton boton-creador-de-entidades">Entity creator</button>
				{/* </router-link> */ }
				<button className="boton boton-salir">Exit</button>
			</div>
		);
	}

	public comenzarNuevoJuego(): void {
		usarComoPlayer(EntidadFactory.crearEntidad("player"));
		crearMundoInicial();
		// void router.push({name: "GameScreen"});
	}

}
