// src/vistas/gamescreen/components/MensajeConsolaVC.vue
<template>
    <div class="mensaje-consola">
        <span v-for="(parteMensaje, index) in mensajeConsola.getMensaje()" :key="index"
                :style="generarEstilo(parteMensaje)">
            {{parteMensaje.texto}}
        </span>
    </div>
</template>

<script lang="ts">
import {Component, Prop, Vue } from "vue-property-decorator";
import { MensajeConsola, PalabrasEstiladas } from "../utils/MensajeConsola";

@Component
export default class ConsolaVC extends Vue  {
    @Prop()
    public mensajeConsola: MensajeConsola;

    public generarEstilo(texto: PalabrasEstiladas): Partial<CSSStyleDeclaration> {
        return {
            color: texto.color ?? "#DDD",
            fontWeight: texto.negrita ? "bold" : "normal"
        };
    }

}
</script>

<style>
.mensaje-consola {
    font-size: 14px;
}

</style>

// src/vistas/gamescreen/components/MensajeConsolaVC.tsx
import React from "react";
import { CSSProperties } from 'styled-components';
import { MensajeConsola, PalabrasEstiladas } from '../utils/MensajeConsola';

export default class MensajeConsolaVC extends React.Component<{ mensaje: MensajeConsola; }> {

    render(): JSX.Element {
        return (
            <div className="mensaje-consola">
                { this.generarMensajeConsola() }
            </div>
        );
    }

    private generarEstilo(texto: PalabrasEstiladas): CSSProperties {
        return {
            color: texto.color ?? "#DDD",
            fontWeight: texto.negrita ? "bold" : "normal"
        };
    }

    private generarMensajeConsola(): JSX.Element[] {
        let partes: JSX.Element[] = [];
        this.props.mensaje.getMensaje().forEach(parteMensaje => {
            partes.push(<span style={ this.generarEstilo(parteMensaje) }> { parteMensaje.texto }</span>);
        });
        return partes;
    }

}
