// src/vistas/gamescreen/components/SideBarVC.vue
<template>
	<div class="side-bar">
		{{ playerPos }}
		<br>
		{{ playercurrentHp }} / {{ playerMaxHp }}
		<br>
		<ConsolaVC></ConsolaVC>
	</div>
</template>

<script lang="ts">
import { Component, Vue } from "vue-property-decorator";
import store from "@/store/store";
import { Posicion } from "@/mapa/Posicion";
import ConsolaVC from "./ConsolaVC.vue";

@Component({
	components: {
		ConsolaVC
	}
})
export default class SideBarVC extends Vue {

	public get playercurrentHp(): number {
		return store.state.player.statsComp.salud.actual;
	}

	public get playerMaxHp(): number {
		return store.state.player.statsComp.salud.max;
	}

	public get playerPos(): Posicion {
		return store.getters.player.posicion as Posicion;
	}

}
</script>

<style scoped>
.side-bar {
	color: white;
	font-size: 1rem;
	background-color: black;
	height: 100vh;
	float: right;
	width: 25%;
}
</style>

// src/vistas/gamescreen/components/SideBarVC.tsx
import React from "react";
import ConsolaVC from "./ConsolaVC";
import { state } from '../../../store/store';
import { Posicion } from "../../../mapa/Posicion";

export default class SideBarVC extends React.Component {

	render() {
		return (
			<div className="side-bar">
				{ Array.of(this.playerPos()) }
				<br />
				{ this.playercurrentHp() } / { this.playerMaxHp() }
				<br />
				<ConsolaVC></ConsolaVC>
			</div>
		);
	}

	public playercurrentHp(): number {
		return state.player.statsComp.salud.actual;
	}

	public playerMaxHp(): number {
		return state.player.statsComp.salud.max;
	}

	public playerPos(): string {
		const pos: Posicion = state.player.posicion;
		return "cx:" + pos.cx + " cy:" + pos.cy + " cz:" + pos.cz + " tx:" + pos.tx + " ty:" + pos.ty;
	}

}
