// src/vistas/creadorentidades/CreadorEntidadesVC.tsx
import React, { useState } from "react";
import Entidad from "../../entidades/Entidad";
import "./styles.css";
import { FlagsForm } from './components/FlagsForm';
import { GraficosForm } from "./components/GraficosForm";
import StatsForm from "./components/statsForm";

export function CreadorEntidadesVC(): JSX.Element {

	const [entidad] = useState(crearNuevaEntidad());

	function crearNuevaEntidad(): Entidad {
		return new Entidad();
	}

	return (
		<>
			<div className="top-bar">
				<button onClick={ () => crearNuevaEntidad() }>Nueva entidad</button>
				<button data-toggle="modal" data-target="#modal-cargar-entidad">Cargar entidad</button>
				<hr />
			</div>
			<div className="container formulario-creador-entidades">
				<span className="contenedor-horizontal">
					<fieldset>
						<legend>Tipo de entidad</legend>
						<select required name="TiposDeEntidad">
							<option value="ACTOR" key="ACTOR">ACTOR</option>
							<option value="TERRENO" key="TERRENO">TERRENO</option>
							<option value="FEATURE" key="FEATURE">FEATURE</option>
						</select>
					</fieldset>
					<fieldset>
						<legend>Nombre</legend>
						<div>
							<input placeholder="Nombre" />
						</div>
					</fieldset>
				</span>
				<GraficosForm entidad={ entidad } />
				<FlagsForm entidad={ entidad } />
				<StatsForm entidad={ entidad } />
				{/* <button onClick={ guardarEntidad }>Guardar</button>
				<ModalCargarEntidadVC ref="modal-cargar-entidad"></ModalCargarEntidadVC> */}
			</div >
		</>
	);

	// function guardarEntidad(): void {
	// 	if (esEntidadValida()) {
	// 		EntidadRepository.persistirEntidades();
	// 	} else {
	// 		console.log("entidad invalida");
	// 	}
	// }

	// function esEntidadValida(): boolean {
	// 	return store.state.tipo && store.state.nombreCompValido && store.state.renderCompValido && store.state.statsCompValido;
	// }
}

// src/vistas/creadorentidades/CreadorEntidadesVC.vue
<template>
	<div class="container formulario-creador-entidades">
		<button @click="crearNuevaEntidad">Nueva entidad</button>
		<button data-toggle="modal" data-target="#modal-cargar-entidad">Cargar entidad</button>
		<hr />
		<TipoFormVC></TipoFormVC>
		<hr />
		<NombreCompFormVC></NombreCompFormVC>
		<hr />
		<RenderCompFormVC></RenderCompFormVC>
		<hr />
		<FlagsFormVC></FlagsFormVC>
		<hr />
		<StatsFormVC></StatsFormVC>
		<hr>
		<button @click="guardarEntidad()">Guardar</button>
		<router-link :to="{name: 'MainScreen'}">
			<button >Salir</button>
		</router-link>
		<ModalCargarEntidadVC ref="modal-cargar-entidad"></ModalCargarEntidadVC>
	</div>
</template>

<script lang="ts">
import { Component, Vue } from "vue-property-decorator";
import Entidad from "@/entidades/Entidad";
import NombreCompFormVC from "./components/nombreCompFormVC.vue"
import TipoFormVC from "./components/tipoFormVC.vue"
import StatsFormVC from "./components/statsFormVC.vue"
import RenderCompFormVC from "./components/renderCompFormVC.vue"
import FlagsFormVC from "./components/flagsFormVC.vue"
import ModalCargarEntidadVC from "./components/modalCargarEntidadVC.vue"
import store from "./store/creadorEntidadesStore";
import { persistirEntidades } from "@/entidades/EntidadRepository";

@Component({
	components: {
		TipoFormVC,
		NombreCompFormVC,
		RenderCompFormVC,
		FlagsFormVC,
		ModalCargarEntidadVC,
		StatsFormVC
	}
})
export default class CreadorEntidadesVC extends Vue {

	public mounted(): void {
		this.crearNuevaEntidad();
	}

	public crearNuevaEntidad(): void {
		store.state.entidadSeleccionada = new Entidad();
	}

	public guardarEntidad(): void {
		if(this.esEntidadValida()){
			persistirEntidades();
		} else {
			console.log("entidad invalida");
		}
	}

   public esEntidadValida(): boolean {
      return store.state.tipo && store.state.nombreCompValido && store.state.renderCompValido && store.state.statsCompValido;
    }

}
</script>

<style>
.formulario-creador-entidades {
	text-align: initial;
}
input {
	margin: 3px;
}
label {
	font-weight: bold;
	font-size: 15px;
	text-decoration: underline;
	margin-bottom: 0px;
	display: block;
}
label.checkbox-label {
	text-decoration: none;
	display: inline;
}
</style>
